services:
  db:
    platform: linux/amd64
    container_name: mysql_db
    # build: ./docker-containers/mysql/
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-ppassword"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 20s
    environment:
      MYSQL_ROOT_PASSWORD: ppassword
      MYSQL_DATABASE: dev
    volumes:
      - data-volume:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
    tty: true
    depends_on:
      db:
        condition: service_healthy

volumes:
  data-volume:
